services:
  backend-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: portfolio-backend-api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../Frontend/public/data:/shared/public/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  telegram-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: portfolio-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - backend-api
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: portfolio-redis
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: portfolio-website_app-network
